### ISSUE TITLE
Convert PTE To Latest High-Level Node.js SDK

### ISSUE THREAD

**Issue by lindluni** [hyperledger/fabric-test#261]
PTE is written using the `fabric-common` package, which is the low-level SDK. Now that the high-level SDK exists and that is the area of focus for future development, PTE should be modified to use the high-level SDK.

Instead of attempting to modify the existing PTE, the rewrite should be a copy and sit in a folder next to PTE (maybe PTEv2) for now. Development will be incremental, code should be pushed frequently, and reviewed and merged frequently, rather than pushing an entire rewrite of the codebase in single commit series.

We should open issues around each component of PTE we need to implement.

**Comment by davidkel** [comment]
see #383 for recommended sunset of PTE and suggested replacement
