### ISSUE TITLE
Recreate PTE Using the Fabric-Go-SDK

### ISSUE THREAD

**Issue by lindluni** [hyperledger/fabric-test#262]
The Go SDK has officially released support for the new high level programming model. Now that this is available we should consider creating a Go-based tool for performing network operation and testing purposes.

The `Operator` tooling is written in Go, as well as Fabric itself. To make use of the larger Fabric ecosystem, it now makes sense to write a tool for drive traffic and operations in Go. This tooling will be a part of the larger Operator ecosystem.

We should open additional issues to encapsulate all the work needed to create a PTE-Go

**Comment by davidkel** [comment]
Although I appreciate the issue WRT operational apis within the various SDKs (node hasn't got one, java does but isn't recommended for use and Go eventually got some capability). For driving business logic the best option for non thin SDKs is still the node SDK. The Go SDK gateway implementation is not as capable or as popular, plus the lack of any movement on the Go SDK implies to me that it feels abandoned.
Going forward with the thin sdks we have a choice of node, java and Go for business logic and all are equal for driving load but it could be interesting to implement all 3 for system test as this tests not only fabric but the sdks as well in a different context

**Comment by davidkel** [comment]
I would say that the Go SDK published here github.com/hyperledger/fabric-sdk-go has been abandoned and I would not recommend using it. Going forward for business level interaction testing we should move the the peer gateway api and for all operational capabilities there really is only osnadmin and peer binaries available. node sdk 2.2 has no official admin api, Java has one but it's not really tested and there is no confidence that it works.

If we do replace PTE I think the supported options are limited
