### ISSUE TITLE
Interop tests failing due to fabric-chaincode-node update

### ISSUE THREAD

**Issue by denyeart** [hyperledger/fabric-test#339]
Interop tests in release-2.2 and release-2.3 are failing since the node update in https://github.com/hyperledger/fabric-chaincode-node/pull/295.

See details at:
https://dev.azure.com/Hyperledger/Fabric-Test/_build?definitionId=114&_a=summary

**Comment by mbwhite** [comment]
https://github.com/hyperledger/fabric-test/pull/340

**Comment by mbwhite** [comment]
@denyeart PR test runs is good... what other branches will need this?  main?
