### ISSUE TITLE
Extend test network to support prometheus/grafana performances framework.

### ISSUE THREAD

**Issue by fraVlaca** [hyperledger/fabric-test#347]
sample of prometheus/grafana that extends test network (add required configs to test network)

**Comment by fraVlaca** [comment]
Added the following enviroment variable to orderer and peers in the docker-compose-test-net file
- _prometheus_ as **metrics provider**  (`CORE_METRICS_PROVIDER=prometheus`)
- **operations service listen address**, orderer: 9443, peer0org1: 9444, peer0org2: 9445 ( i.e. `ORDERER_OPERATIONS_LISTENADDRESS=orderer.example.com:9443`)

**Comment by fraVlaca** [comment]
Exposed the **ports** for the respecting operations service address ( orderer: 9443, peer0org1: 9444, peer0org2: 9445)

**Comment by davidkel** [comment]
@denyeart Could you close this issue please, I've moved it to 
https://github.com/hyperledger/fabric-samples/issues/544
