### ISSUE TITLE
Performances Gateway - Proposal request processing time inconsistency

### ISSUE THREAD

**Issue by fraVlaca** [hyperledger/fabric-test#349]
investigate why is proposal request processing taking 2 seconds, while most other operations are done in milliseconds

**Comment by fraVlaca** [comment]
### Premises
Issue #346 shows how the proposal duration and StateDb commit time are drasticaly impacted by an increase of concurrent trancsactions.
The rate of change of the proposal durations is significantly bigger than the concurency rate of change.
This issue could be caused by a very small block size; lots of concurrent transactions trying to be submitted on a small sized block could indeed cause proposal duration, latency and state db commit time to increase drammaticaly (as showed on #346)

**Comment by fraVlaca** [comment]
### Analysis
- Use Debug Analysis to see the lifecycle of a transaction and find bottleneck.
- Investigate if, by increasing the number of transactions of each block, we are able to solve the issue and reduce the proposal duration for each transaction.

**Comment by fraVlaca** [comment]
### Results
1. Increasing the block size do not affect Proposal duration metric
          - after increasing the MaxMessageCount to 500 and then 1000 I still got very high Proposal Durations for the endorser 

2. Debug Analysis doesn't reflect what showed by the endorser proposal duration metric
          - I couldn't find any bottleneck or discrepancy that reflects an high Proposal duration time, below are some results of 
           the debug analysis carried on

**Comment by fraVlaca** [comment]
<img width="1335" alt="Screenshot 2022-01-13 at 10 41 06" src="https://user-images.githubusercontent.com/86831094/149343542-84735852-ac8a-471a-a1af-e4a3f2adb7d8.png">

<img width="1346" alt="Screenshot 2022-01-13 at 10 48 51" src="https://user-images.githubusercontent.com/86831094/149343594-6a4c48b7-02c9-40be-abfd-4f44704fe568.png">

<img width="1337" alt="Screenshot 2022-01-13 at 11 55 09" src="https://user-images.githubusercontent.com/86831094/149343670-19fbe9d6-6560-4d85-81b9-cc8a93ed3527.png">

**Comment by fraVlaca** [comment]
### Considerations
Using debug analysis I was able to analyse the lifecycle of a transaction and ascertain that what reported by the peer metric for the proposal duration was not reflected on what seen on the peer logs; the major time taken by an operation was around 100-200ms, which was nowhere near what reported by the Proposal duration metric of the peer operations service.

As a result of the above results we can consider the following **assumptions**:
- the proposal duration metric reported by the peer operations server is not reliable or using a different unit of measurement from the other metrcis (i.e. ms instead of s) 
- the transactions lifecycle analysis performed is imprecise or somehow erroneous

**Comment by davidkel** [comment]
@fraVlaca @denyeart  I think this was due to the grafana graph showing a sum of the proposal response times rather than an average. I think this issue can be closed

**Comment by fraVlaca** [comment]
100% agree - I updated the dashboard to keep count and divide the metric by the total number of proposal received. Here is how it looks like now and it is in line to what was showed by the debug analysis:
<img width="1720" alt="Screenshot 2022-01-17 at 16 35 59" src="https://user-images.githubusercontent.com/86831094/149808666-59e3e2eb-1faa-4087-8348-1e4c5269b58e.png">

**Comment by denyeart** [comment]
Thanks @fraVlaca ! Closing...
