### ISSUE TITLE
Automate configuration of a performance testbed for a Fabric Developer

### ISSUE THREAD

**Issue by fraVlaca** [hyperledger/fabric-test#351]
### Automate configuration of a provisioned environment to enable a developer provided fabric to be driven by a caliper workload 

- [ ] investigate the suitability for the environment to be all provisioned VMs such that the results are consistent and comparable within the lifetime of those provisioned VMs
- [ ] provide an environment to be able to stand up a fabric network with local dev changes
- [ ] provide capability to be able to extend that environment to include prometheus and grafana servers with a starter set of queries and graphs
- [ ] reference caliper and caliper-benchmarks wrt defining and running a caliper based benchmark to perform comparisons

At this time there is no facilities available to be able to provision systems for this activity. It will therefore be the responsibility of contributors to source their own appropriate systems in order to be able to run benchmarks to test their code changes.

Further, this will initially be a BYOF (Bring Your Own Fabric) environment where the fabric processes are either run natively or using a lightweight container environment such as docker and as such the processes are still cleanly exposed as though they were native and network access is trivial via a single SUT ipaddress. It will be upto the developer to start/stop the fabric processes as well as be able to deploy their own chaincode.

**Comment by davidkel** [comment]
Prototype being developed here https://github.com/davidkel/provision-performance

**Comment by fraVlaca** [comment]
Checking that provisioned VMs give consistent results.
Will bring up test environments and run benchmark 5 times and check that:
- avg cpu remains the same
- max TPS remains the same
- disk i/o rate is consistent
- fabric metrics remain consistent

**Comment by fraVlaca** [comment]
VMs might be at risk of having noisy neighbours representing an huge problem to get consistent results. 
Alain Fisher or Barry Packman are part of the Hursley Fire teams. Ask them help to clarify and address the problem.

**Comment by fraVlaca** [comment]
**Fyre slots**
Slots provides dedicated system resources via a single VM sitting on top of a KVM hypervisor.  Only one slot VM will be active on any given physical system at a time.  This ensures that there is no resource contention on that machine.  When you shut down a slot system, via the provided APIs, the machine that was hosting the slot VM can then be re-used by another workload.  When you are ready to power your slot VM back on it will be booted onto a machine from the pool.

***Note - Fyre Slots is handled via OneTicket requests - You will be asked to provide a business justification as to why you can not use a standard VM for your workload**

**Comment by fraVlaca** [comment]
**What is Fyre Dedicated and how is it different from slots**

Fyre Dedicated is very similar to slots in that it provides dedicated system resources to a single VM running on top of a KVM hypervisor.  The main difference between Slots and Dedicated is that the physical machine that the Dedicated VM runs on will always be the same.  When a Dedicated system is shut down, via the provided APIs, the underlying hardware is not returned to the pool for re-use by other workloads and will remain dedicated to the single VM.

*Note - Fyre Dedicated is handled via OneTicket requests - You will be asked to provide a business justification as to why you can not use a standard VM for your workload and why your workload has to be tied specifically to one machine.  It is preferred that Slots is used, whenever possible, to ensure that we are able to maximize the use of our physical indfrastructure

**Comment by davidkel** [comment]
Done
