### ISSUE TITLE
Privacy leakage in mapkeys.go

### ISSUE THREAD

**Issue by ghost** [hyperledger/fabric-test#511]
The "Invoke" function in chaincodes/mapkeys/go/mapkeys.go gets the private data directly via function parameters, which will be included in the transaction and all peers can access.

**Comment by denyeart** [comment]
Thank you, it's ok though, this is a legacy test that is not run and will likely get retired.
The integration tests in core fabric repository and fabric-samples repository demonstrate the correct usage patterns. We direct people to those tests instead.
